# Generated by Django 5.1.1 on 2024-09-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_customuser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_token',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
